export const coffeeBeanMenu = [
    {
        id: 1,
        name: 'Brazil Cerrado',
        image: '/Image/coffeeBeanMenu/brazil_cerrado.jpg',
        description: 'Brazil Cerrado',
        price: 4.87,        
    },
    {
        id: 2,
        name: 'Brazil Yellow Bourbon',
        image: '/Image/coffeeBeanMenu/brazil_yellow_bourbon.jpg',
        description: 'Brazil yellow bourbon',
        price: 6.0,        
    },
    {
      id: 3,
      name: 'Colombia Supremo',
      image: '/Image/coffeeBeanMenu/colombia_supremo.jpg',
      description: 'Colombia Supremo',
      price: 5.62,      
    },
    {
      id: 4,
      name: 'Costa Rica Tarrazu',
      image: '/Image/coffeeBeanMenu/costa_rica_tarrazu.jpg',
      description: 'Costa Rica Tarrazu',
      price: 6.37,      
    },
    {
      id: 5,
      name: 'Ethiopia Konga',
      image: '/Image/coffeeBeanMenu/ethiopia_konga.jpg',
      description: 'Ethiopia Konga',
      price: 11.62,      
    },
    {
      id: 6,
      name: 'Ethiopia Sidamo G2',
      image: '/Image/coffeeBeanMenu/ethiopia_sidamo_g2.jpg',
      description: 'Ethiopia Sidamo G2',
      price: 6.0,       
    },
    {
      id: 7,
      name: 'Ethiopia Yirgacheffe G2',
      image: '/Image/coffeeBeanMenu/ethiopia_yirgacheffe_g2.jpg',
      description: 'Ethiopia Yirgacheffe',
      price: 6.37,      
    },
    {
      id: 8,
      name: 'Guatemala Antigua',
      image: '/Image/coffeeBeanMenu/guatemala_antigua.jpg',
      description: 'Guatemala Antigua',
      price: 6.37,      
    },
    {
      id: 9,
      name: 'India Monsooned Malabar AA',
      image: '/Image/coffeeBeanMenu/india_monsoon_malabar_AA.jpg',
      description: 'India Monsooned Malabar',
      price: 6.0,    
    },
    {
      id: 10,
      name: 'India Mysoore Nuggets',
      image: '/Image/coffeeBeanMenu/india_mysore_nuggets_extra_bold.jpg',
      description: 'India Mysoore Nuggets',
      price: 6.0,      
    },
    {
      id: 11,
      name: 'Indonesia Sumatra Mandheling',
      image: '/Image/coffeeBeanMenu/indonesia_mandheling_g1.jpg',
      description: 'Indonesia Sumatra Mandheling',
      price: 7.12,      
    },
    {
      id: 12,
      name: 'Kenya AA',
      image: '/Image/coffeeBeanMenu/kenya_AA.jpg',
      description: 'Kenya AA',
      price: 8.24,      
    },
    {
      id: 13,
      name: 'Kenya Peaberry',
      image: '/Image/coffeeBeanMenu/kenya_peaberry.jpg',
      description: 'Kenya Peaberry',
      price: 6.75,
    },
    {
      id: 14,
      name: 'Cosorong Blend',
      image: '/Image/coffeeBeanMenu/cosorong_blend.jpg',
      description: 'Cosorong Blend',
      price: 5.61,
    },
    {
      id: 15,
      name: 'Orotsee Blend',
      image: '/Image/coffeeBeanMenu/orotsee_blend.jpg',
      description: 'Orotsee Blend',
      price: 6.0,
    },
    {
      id: 16,
      name: 'Dark Blend',
      image: '/Image/coffeeBeanMenu/dark_blend.jpg',
      description: 'Dark Blend',
      price: 5.24,
    },
]
export default coffeeBeanMenu;