export const coffeeBeanMenu = [
    {
        id: 1,
        name: 'Brazil Cerrado',
        image: '/Image/coffeeBeanMenu/brazil_cerrado.jpg',
        description: {
          origin: 'Brazil',
          region: 'Cerrado',
          process: 'Natural',
          altitude: '900-1,200m',
          varietal: 'Mundo Novo, Catuai, Acaia',
          harvest_time: 'May - November',
          grade: 'NY2, SC 17/18, FC',
          tasting_map: {
            acidity: 3/5,
            body: 3/5,
            sweetness: 3/5,
            flavor: 3/5,
            bitterness: 2/5,
          },
          roasting_point: '/Image/roastingPoint/brazil_cerrado.jpg',
        },
        price: 4.87,        
    },
    {
        id: 2,
        name: 'Brazil Yellow Bourbon',
        image: '/Image/coffeeBeanMenu/brazil_yellow_bourbon.jpg',
        description: {
          origin: 'Brazil',
          region: 'Sul De Minas',
          process: 'Pulped Natural',
          altitude: '1,100-1,200m',
          varietal: 'Yellow Bourbon',
          harvest_time: 'May - September',
          grade: 'NY2',
          tasting_map: {
            acidity: 2/5,
            body: 3/5,
            sweetness: 3/5,
            flavor: 2/5,
            bitterness: 3/5,
          },
          roasting_point: '/Image/roastingPoint/brazil_yellow_bourbon.jpg',
        
        },
        price: 6.0,        
    },
    {
      id: 3,
      name: 'Colombia Supremo',
      image: '/Image/coffeeBeanMenu/colombia_supremo.jpg',
      description: {
        origin: 'Colombia',
        region: 'Caldas, Risaralda',
        process: 'Washed',
        altitude: '1,200-1,800m',
        varietal: 'Caturra & Castillo',
        harvest_time: 'October - November, March - April',
        grade: 'Supremo',
        tasting_map: {
          acidity: 3/5,
          body: 3/5,
          sweetness: 3/5,
          flavor: 3/5,
          bitterness: 3/5,
        },
        roasting_point: '/Image/roastingPoint/colombia_supremo.jpg',
      },
      price: 5.62,      
    },
    {
      id: 4,
      name: 'Costa Rica Tarrazu',
      image: '/Image/coffeeBeanMenu/costa_rica_tarrazu.jpg',
      description: {
        origin: 'Costa Rica',
        region: 'Tarrazu',
        process: 'Fully Washed, Machine-Dried',
        altitude: '1,200-1,400m',
        varietal: 'Caturra & Catuai',
        harvest_time: 'October - February',
        grade: 'SHB',
        tasting_map: {
          acidity: 3/5,
          body: 3/5,
          sweetness: 3/5,
          flavor: 3/5,
          bitterness: 3/5,
        },
        roasting_point: '/Image/roastingPoint/costa_rica_tarrazu.jpg',
      
      },
      price: 6.37,      
    },
    {
      id: 5,
      name: 'Ethiopia Konga',
      image: '/Image/coffeeBeanMenu/ethiopia_konga.jpg',
      description: {
        origin: 'Ethiopia',
        region: 'Gedeo, Yirgacheffe',
        process: 'Washed, Sun-Dried',
        altitude: '1,800-2,200m',
        varietal: 'Heirloom',
        harvest_time: 'November - January',
        grade: 'Grade 1',
        tasting_map: {
          acidity: 4/5,
          body: 3/5,
          sweetness: 3/5,
          flavor: 3/5,
          bitterness: 2/5,
        },
        roasting_point: '/Image/roastingPoint/ethiopia_konga.jpg',
      },
      price: 11.62,      
    },
    {
      id: 6,
      name: 'Ethiopia Sidamo G2',
      image: '/Image/coffeeBeanMenu/ethiopia_sidamo_g2.jpg',
      description: {
        origin: 'Ethiopia',
        region: 'Sidamo',
        process: 'Washed',
        altitude: '1,600-1,900m',
        varietal: 'Heirloom',
        harvest_time: 'October - January',
        grade: 'G2',
        tasting_map: {
          acidity: 3/5,
          body: 3/5,
          sweetness: 3/5,
          flavor: 4/5,
          bitterness: 2/5,
        },
        roasting_point: '/Image/roastingPoint/ethiopia_sidamo_g2.jpg',
      },
      price: 6.0,       
    },
    {
      id: 7,
      name: 'Ethiopia Yirgacheffe G2',
      image: '/Image/coffeeBeanMenu/ethiopia_yirgacheffe_g2.jpg',
      description: {
        origin: 'Ethiopia',
        region: 'Yirgacheffe',
        process: 'Washed',
        altitude: '1,770-2,200m',
        varietal: 'Heirloom',
        harvest_time: 'October - January',
        grade: 'G2',
        tasting_map: {
          acidity: 3/5,
          body: 2/5,
          sweetness: 3/5,
          flavor: 3/5,
          bitterness: 2/5,
        },
        roasting_point: '/Image/roastingPoint/ethiopia_yirgacheffe_g2.jpg',
      
      },
      price: 6.37,      
    },
    {
      id: 8,
      name: 'Guatemala Antigua',
      image: '/Image/coffeeBeanMenu/guatemala_antigua.jpg',
      description: {
        origin: 'Guatemala',
        region: 'Antigua',
        process: 'Washed',
        altitude: '1,500-1,700m',
        varietal: 'Bourbon, Caturra',
        harvest_time: 'December - March',
        grade: 'SHB',
        tasting_map: {
          acidity: 2/5,
          body: 4/5,
          sweetness: 3/5,
          flavor: 3/5,
          bitterness: 4/5,
        },
        roasting_point: '/Image/roastingPoint/guatemala_antigua.jpg',
      
      
      },
      price: 6.37,      
    },
    {
      id: 9,
      name: 'India Monsooned Malabar AA',
      image: '/Image/coffeeBeanMenu/india_monsoon_malabar_AA.jpg',
      description: {
        origin: 'India',
        region: 'Malabar',
        process: 'Sun-dried',
        altitude: '900-1,100m',
        varietal: 'Kent / Selection 795',
        harvest_time: 'July - October',
        grade: 'AA',
        tasting_map: {
          acidity: 1/5,
          body: 3/5,
          sweetness: 3/5,
          flavor: 4/5,
          bitterness: 3/5,
        },
        roasting_point: '/Image/roastingPoint/india_monsoon_malabar_AA.jpg',
      },
      price: 6.0,    
    },
    {
      id: 10,
      name: 'India Mysoore Nuggets',
      image: '/Image/coffeeBeanMenu/india_mysore_nuggets_extra_bold.jpg',
      description: {
        origin: 'India',
        region: 'Chikmagalure, Giri, Manjarabad',
        process: 'Washed',
        altitude: '1,000-1,100m',
        varietal: 'S795, SLN5, SLN9, Catimor, Catuai, Chandragiri, Cauvety',
        harvest_time: 'November - February',
        grade: 'Scr-18/19',
        tasting_map: {
          acidity: 2/5,
          body: 3/5,
          sweetness: 3/5,
          flavor: 3/5,
          bitterness: 3/5,
        },
        roasting_point: '/Image/roastingPoint/india_mysore_nuggets_extra_bold.jpg',
      },
      price: 6.0,      
    },
    {
      id: 11,
      name: 'Indonesia Sumatra Mandheling',
      image: '/Image/coffeeBeanMenu/indonesia_mandheling_g1.jpg',
      description: 'Indonesia Sumatra Mandheling',
      price: 7.12,      
    },
    {
      id: 12,
      name: 'Kenya AA',
      image: '/Image/coffeeBeanMenu/kenya_AA.jpg',
      description: 'Kenya AA',
      price: 8.24,      
    },
    {
      id: 13,
      name: 'Kenya Peaberry',
      image: '/Image/coffeeBeanMenu/kenya_peaberry.jpg',
      description: 'Kenya Peaberry',
      price: 6.75,
    },
    {
      id: 14,
      name: 'Cosorong Blend',
      image: '/Image/coffeeBeanMenu/cosorong_blend.jpg',
      description: 'Cosorong Blend',
      price: 5.61,
    },
    {
      id: 15,
      name: 'Orotsee Blend',
      image: '/Image/coffeeBeanMenu/orotsee_blend.jpg',
      description: 'Orotsee Blend',
      price: 6.0,
    },
    {
      id: 16,
      name: 'Dark Blend',
      image: '/Image/coffeeBeanMenu/dark_blend.jpg',
      description: 'Dark Blend',
      price: 5.24,
    },
]
export default coffeeBeanMenu;