export const coffeeBeanMenu = [
    {
        id: 1,
        name: 'Brazil Cerrado',
        image: '/Image/coffeeBeanMenu/brazil_cerrado.jpg',
        description: {
          description: 'Cerrado is a type of coffee bean that is grown in the Cerrado region of Brazil. It is named after the Cerrado region of Brazil.',
          origin: 'Brazil',
          region: 'Cerrado',
          process: 'Natural',
          altitude: '900-1,200m',
          varietal: 'Mundo Novo, Catuai, Acaia',
          harvest_time: 'May - November',
          grade: 'NY2, SC 17/18, FC',
          tasting_map: {
            acidity: 3/5 * 100,
            body: 3/5 * 100,
            sweetness: 3/5 * 100,
            flavor: 3/5 * 100,
            bitterness: 2/5 * 100,
          },
          roasting_point: '/Image/roastingPoint/brazil_cerrado.jpg',
          region_map: '/Image/regionMap/brazil_cerrado.jpg',
        },
        price: 4.87,
        nodtification: {
          title: 'Brazil Cerrado',
          description: 'This coffee bean is grown in the Cerrado region of Brazil, which is famous for its coffee. It tastes sweet as caramel and savory nut scents.',
          alt: 'First Notification',
          image: '/Image/noticeMenu/coffeeBeans1.jpg',
        },        
    },
    {
        id: 2,
        name: 'Brazil Yellow Bourbon',
        image: '/Image/coffeeBeanMenu/brazil_yellow_bourbon.jpg',
        description: {
          description: 'Yellow Bourbon is a type of coffee bean that is grown in the Sul De Minas region of Brazil. It is named after the Bourbon region of Brazil.',
          origin: 'Brazil',
          region: 'Sul De Minas',
          process: 'Pulped Natural',
          altitude: '1,100-1,200m',
          varietal: 'Yellow Bourbon',
          harvest_time: 'May - September',
          grade: 'NY2',
          tasting_map: {
            acidity: 2/5 * 100,
            body: 3/5 * 100,
            sweetness: 3/5 * 100,
            flavor: 2/5 * 100,
            bitterness: 3/5 * 100,
          },
          roasting_point: '/Image/roastingPoint/brazil_yellow_bourbon.jpg',
          region_map: '/Image/regionMap/brazil_yellow_bourbon.jpg',
        },
        price: 6.0,
        nodtification: {
          title: 'Brazil Yellow Bourbon',
          description: 'This coffee bean is grown in the Sul De Minas region of Brazil, which is famous for its coffee. It tastes sweet as caramel and savory nut scents.',
          alt: 'First Notification',
          image: '/Image/noticeMenu/coffeeBeans2.jpg',
        },        
    },
    {
      id: 3,
      name: 'Colombia Supremo',
      image: '/Image/coffeeBeanMenu/colombia_supremo.jpg',
      description: {
        description: 'Supremo is a type of coffee bean that is grown in the Huila region of Colombia. It is named after the Supremo region of Colombia.',
        origin: 'Colombia',
        region: 'Caldas, Risaralda',
        process: 'Washed',
        altitude: '1,200-1,800m',
        varietal: 'Caturra & Castillo',
        harvest_time: 'October - November, March - April',
        grade: 'Supremo',
        tasting_map: {
          acidity: 3/5 * 100,
          body: 3/5 * 100,
          sweetness: 3/5 * 100,
          flavor: 3/5 * 100,
          bitterness: 3/5 * 100,
        },
        roasting_point: '/Image/roastingPoint/colombia_supremo.jpg',
        region_map: '/Image/regionMap/colombia_supremo.jpg',
      },
      price: 5.62, 
      notification: {
        title: 'Colombia Supremo',
        description: 'This coffee bean is grown in the Huila region of Colombia, which is famous for its coffee. It tastes sweet as caramel and savory nut scents.',
        alt: 'First Notification',
        image: '/Image/noticeMenu/coffeeBeans3.jpg',
      },     
    },
    {
      id: 4,
      name: 'Costa Rica Tarrazu',
      image: '/Image/coffeeBeanMenu/costa_rica_tarrazu.jpg',
      description: {
        description: 'Tarrazu is a type of coffee bean that is grown in the Tarrazu region of Costa Rica. It is named after the Tarrazu region of Costa Rica.',
        origin: 'Costa Rica',
        region: 'Tarrazu',
        process: 'Fully Washed, Machine-Dried',
        altitude: '1,200-1,400m',
        varietal: 'Caturra & Catuai',
        harvest_time: 'October - February',
        grade: 'SHB',
        tasting_map: {
          acidity: 3/5 * 100,
          body: 3/5 * 100,
          sweetness: 3/5 * 100,
          flavor: 3/5 * 100,
          bitterness: 3/5 * 100,
        },
        roasting_point: '/Image/roastingPoint/costa_rica_tarrazu.jpg',
        region_map: '/Image/regionMap/costa_rica_tarrazu.jpg',      
      },
      price: 6.37,   
      notification: {
        title: 'Costa Rica Tarrazu',
        description: 'This coffee bean is grown in the Tarrazu region of Costa Rica, which is famous for its coffee. It tastes sweet as caramel and savory nut scents.',
        alt: 'First Notification',
        image: '/Image/noticeMenu/coffeeBeans4.jpg',
      },   
    },
    {
      id: 5,
      name: 'Ethiopia Konga',
      image: '/Image/coffeeBeanMenu/ethiopia_konga.jpg',
      description: {
        description: 'Konga is a type of coffee bean that is grown in the Konga region of Ethiopia. It is named after the Konga region of Ethiopia.',
        origin: 'Ethiopia',
        region: 'Gedeo, Yirgacheffe',
        process: 'Washed, Sun-Dried',
        altitude: '1,800-2,200m',
        varietal: 'Heirloom',
        harvest_time: 'November - January',
        grade: 'Grade 1',
        tasting_map: {
          acidity: 4/5 * 100,
          body: 3/5 * 100,
          sweetness: 3/5 * 100,
          flavor: 3/5 * 100,
          bitterness: 2/5 * 100,
        },
        roasting_point: '/Image/roastingPoint/ethiopia_konga.jpg',
        region_map: '/Image/regionMap/ethiopia_konga.jpg',
      },
      price: 11.62,
      notification: {
        title: 'Ethiopia Konga',
        description: 'This coffee bean is grown in the Konga region of Ethiopia, which is famous for its coffee. It tastes sweet as caramel and savory nut scents.',
        alt: 'First Notification',
        image: '/Image/noticeMenu/coffeeBeans5.jpg',
      },      
    },
    {
      id: 6,
      name: 'Ethiopia Sidamo G2',
      image: '/Image/coffeeBeanMenu/ethiopia_sidamo_g2.jpg',
      description: {
        description: 'Sidamo is a type of coffee bean that is grown in the Sidamo region of Ethiopia. It is named after the Sidamo people who produce and export coffee beans in the Sidamo region of Ethiopia.',
        origin: 'Ethiopia',
        region: 'Sidamo',
        process: 'Washed',
        altitude: '1,600-1,900m',
        varietal: 'Heirloom',
        harvest_time: 'October - January',
        grade: 'G2',
        tasting_map: {
          acidity: 3/5 * 100,
          body: 3/5 * 100,
          sweetness: 3/5 * 100,
          flavor: 4/5 * 100,
          bitterness: 2/5 * 100,
        },
        roasting_point: '/Image/roastingPoint/ethiopia_sidamo_g2.jpg',
        region_map: '/Image/regionMap/ethiopia_sidamo_g2.jpg',
      },
      price: 6.0,       
    },
    {
      id: 7,
      name: 'Ethiopia Yirgacheffe G2',
      image: '/Image/coffeeBeanMenu/ethiopia_yirgacheffe_g2.jpg',
      description: {
        description: 'Yirgacheffe is a type of coffee bean that is grown in the Yirgacheffe region of Ethiopia. It is named after the town of Yirgacheffe in Ethiopia.',
        origin: 'Ethiopia',
        region: 'Yirgacheffe',
        process: 'Washed',
        altitude: '1,770-2,200m',
        varietal: 'Heirloom',
        harvest_time: 'October - January',
        grade: 'G2',
        tasting_map: {
          acidity: 3/5 * 100,
          body: 2/5 * 100,
          sweetness: 3/5 * 100,
          flavor: 3/5 * 100,
          bitterness: 2/5 * 100,
        },
        roasting_point: '/Image/roastingPoint/ethiopia_yirgacheffe_g2.jpg',
        region_map: '/Image/regionMap/ethiopia_yirgacheffe_g2.png',      
      },
      price: 6.37,      
    },
    {
      id: 8,
      name: 'Guatemala Antigua',
      image: '/Image/coffeeBeanMenu/guatemala_antigua.jpg',
      description: {
        description: 'Antigua is a type of coffee bean that is grown in the Antigua region of Guatemala. It is named after the city of Antigua in Guatemala.',
        origin: 'Guatemala',
        region: 'Antigua',
        process: 'Washed',
        altitude: '1,500-1,700m',
        varietal: 'Bourbon, Caturra',
        harvest_time: 'December - March',
        grade: 'SHB',
        tasting_map: {
          acidity: 2/5 * 100,
          body: 4/5 * 100,
          sweetness: 3/5 * 100,
          flavor: 3/5 * 100,
          bitterness: 4/5 * 100,
        },
        roasting_point: '/Image/roastingPoint/guatemala_antigua.jpg',
        region_map: '/Image/regionMap/guatemala_antigua.jpg',
      },
      price: 6.37,      
    },
    {
      id: 9,
      name: 'India Monsooned Malabar AA',
      image: '/Image/coffeeBeanMenu/india_monsoon_malabar_AA.jpg',
      description: {
        description: 'Monsooned Malabar is a type of coffee bean that is grown in the south of India. It is named after the Malabar Coast of India where the coffee beans are exposed to the monsoon winds of the Arabian Sea.',
        origin: 'India',
        region: 'Malabar',
        process: 'Sun-dried',
        altitude: '900-1,100m',
        varietal: 'Kent / Selection 795',
        harvest_time: 'July - October',
        grade: 'AA',
        tasting_map: {
          acidity: 1/5 * 100,
          body: 3/5 * 100,
          sweetness: 3/5 * 100,
          flavor: 4/5 * 100,
          bitterness: 3/5 * 100,
        },
        roasting_point: '/Image/roastingPoint/india_monsoon_malabar_AA.jpg',
        region_map: '/Image/regionMap/india_monsoon_malabar_AA.jpg',
      },
      price: 6.0,    
    },
    {
      id: 10,
      name: 'India Mysoore Nuggets',
      image: '/Image/coffeeBeanMenu/india_mysore_nuggets_extra_bold.jpg',
      description: {
        description: 'Mysoore is a type of coffee bean that is grown in the south of India. It is named after the city of Mysore in Karnataka, India.',
        origin: 'India',
        region: 'Chikmagalure, Giri, Manjarabad',
        process: 'Washed',
        altitude: '1,000-1,100m',
        varietal: 'S795, SLN5, SLN9, Catimor, Catuai, Chandragiri, Cauvety',
        harvest_time: 'November - February',
        grade: 'Scr-18/19',
        tasting_map: {
          acidity: 2/5 * 100,
          body: 3/5 * 100,
          sweetness: 3/5 * 100,
          flavor: 3/5 * 100,
          bitterness: 3/5 * 100,
        },
        roasting_point: '/Image/roastingPoint/india_mysore_nuggets_extra_bold.jpg',
        region_map: '/Image/regionMap/india_mysore_nuggets_extra_bold.png',
      },
      price: 6.0,      
    },
    {
      id: 11,
      name: 'Indonesia Sumatra Mandheling',
      image: '/Image/coffeeBeanMenu/indonesia_mandheling_g1.jpg',
      description: {
        description: 'Mandheling is a type of coffee bean that is grown in the north of Sumatra, Indonesia. It is named after the Mandailing people who produce and export coffee beans in the Tapanuli region of Sumatra.',
        origin: 'Indonesia',
        region: 'Sumatra',
        process: 'Wet-Hulled',
        altitude: '1,200-1,500m',
        varietal: 'Catimor, Typica',
        harvest_time: 'October - December, March - June',
        grade: 'G1',
        tasting_map: {
          acidity: 2/5 * 100,
          body: 4/5 * 100,
          sweetness: 3/5 * 100,
          flavor: 3/5 * 100,
          bitterness: 4/5 * 100,
        },
        roasting_point: '/Image/roastingPoint/indonesia_mandheling_g1.jpg',
        region_map: '/Image/regionMap/indonesia_mandheling_g1.png',      
      },
      price: 7.12,      
    },
    {
      id: 12,
      name: 'Kenya AA',
      image: '/Image/coffeeBeanMenu/kenya_AA.jpg',
      description: {
        description: 'AA is the highest grade of Kenyan coffee based on the size of the bean. AA is the largest bean size and AB is the second largest.',
        origin: 'Kenya',
        region: 'Kiambu',
        process: 'Washed',
        altitude: '1,700m',
        varietal: 'SL28, Ruiru 11',
        harvest_time: 'October - December, June - July',
        grade: 'AA',
        tasting_map: {
          acidity: 3/5 * 100,
          body: 3/5 * 100,
          sweetness: 3/5 * 100,
          flavor: 3/5 * 100,
          bitterness: 3/5 * 100,
        },
        roasting_point: '/Image/roastingPoint/kenya_AA.jpg',
        region_map: '/Image/regionMap/kenya_AA.jpg',
      },
      price: 8.24,      
    },
    {
      id: 13,
      name: 'Kenya Peaberry',
      image: '/Image/coffeeBeanMenu/kenya_peaberry.jpg',
      description: {
        description: 'Peaberry is a type of coffee bean that is round and small. It is a natural mutation of the coffee bean that occurs inside the coffee cherry so only one bean is produced inside the cherry instead of the usual two.',
        origin: 'Kenya',
        region: 'Kiambu',
        process: 'Washed',
        altitude: '1,500 - 1,850m',
        varietal: 'SL28, SL34, Batian, Ruiru11',
        harvest_time: 'October - December, June - July',
        grade: 'Peaberry, FAQ',
        tasting_map: {
          acidity: 3/5 * 100,
          body: 3/5 * 100,
          sweetness: 3/5 * 100,
          flavor: 3/5 * 100,
          bitterness: 3/5 * 100,
        },
        roasting_point: '/Image/roastingPoint/kenya_peaberry.jpg',
        region_map: '/Image/regionMap/kenya_peaberry.jpg',
      },
      price: 6.75,
    },
    {
      id: 14,
      name: 'Cosorong Blend',
      image: '/Image/coffeeBeanMenu/cosorong_blend.jpg',
      description: {
        description: 'Cosorong means "Aromatic" in Korean and it is a blend of more than 2 different beans from more than 2 different countries.',
        origin: 'N/A',
        region: 'N/A',
        process: 'N/A',
        altitude: 'N/A',
        varietal: 'N/A',
        harvest_time: 'N/A',
        grade: 'N/A',
        tasting_map: {
          acidity: 3/5 * 100,
          body: 3/5 * 100,
          sweetness: 3/5 * 100,
          flavor: 3/5 * 100,
          bitterness: 3/5 * 100,
        },
        roasting_point: '/Image/roastingPoint/cosorong_blend.jpg',
        region_map: '/Image/regionMap/cosorong_blend.jpg',      
      },
      price: 5.61,
    },
    {
      id: 15,
      name: 'Orotsee Blend',
      image: '/Image/coffeeBeanMenu/orotsee_blend.jpg',
      description: {
        description: 'Orotsee means "Fully intact" in Korean and it is a blend of more than 2 different beans from more than 2 different countries.',
        origin: 'N/A',
        region: 'N/A',
        process: 'N/A',
        altitude: 'N/A',
        varietal: 'N/A',
        harvest_time: 'N/A',
        grade: 'N/A',
        tasting_map: {
          acidity: 2/5 * 100,
          body: 4/5 * 100,
          sweetness: 3/5 * 100,
          flavor: 3/5 * 100,
          bitterness: 4/5 * 100,
        },
        roasting_point: '/Image/roastingPoint/orotsee_blend.jpg',
        region_map: '/Image/regionMap/orotsee_blend.jpg',
      },
      price: 6.0,
    },
    {
      id: 16,
      name: 'Dark Blend',
      image: '/Image/coffeeBeanMenu/dark_blend.jpg',
      description: {
        description: 'Dark Blend tastes like savory dark chocolate and it is a blend of more than 2 different beans from more than 2 different countries.',
        origin: 'N/A',
        region: 'N/A',
        process: 'N/A',
        altitude: 'N/A',
        varietal: 'N/A',
        harvest_time: 'N/A',
        grade: 'N/A',
        tasting_map: {
          acidity: 1/5 * 100,
          body: 4/5 * 100,
          sweetness: 2/5 * 100,
          flavor: 3/5 * 100,
          bitterness: 4/5 * 100,
        },
        roasting_point: '/Image/roastingPoint/dark_blend.jpg',
        region_map: '/Image/regionMap/dark_blend.jpg',
      },
      price: 5.24,
    },
]
export default coffeeBeanMenu;